import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";

import { TRPCReactProvider } from "~/trpc/react";
import { Navigation } from "./_components/Navigation";
import { Footer } from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <Analytics />
      <body className="flex min-h-screen flex-col bg-gradient-to-b from-[#14181C] to-black text-white">
        <Navigation />

        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
